import os
import sys

if sys.platform.startswith('win'):
    CCFLAGS = ['/EHsc', '/nologo']
    LIBS = []
else:
    CCFLAGS = ''
    LIBS = ['pthread']

Program(
    'gtest.cpp', 
    CPPPATH=os.environ.get('INCLUDE'),
    CCFLAGS=CCFLAGS,
    LIBPATH=os.environ.get('LIBPATH'),
    LIBS=['gtest'] + LIBS,
)

for filename in ('boost_success.cpp', 'boost_failure.cpp', 'boost_error.cpp'):
    Program(
        filename,
        CPPPATH=os.environ.get('INCLUDE'),
        CCFLAGS=CCFLAGS,
    )
